version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_checkout:
      - git submodule update --init --recursive
    post_install:
      - ./build.sh python
      - pip install build/dist/*.whl --upgrade --no-deps
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements.txt
    - requirements: mast3r/requirements.txt
    - requirements: mast3r/dust3r/requirements.txt
